'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var FINALIZE_SETUP = 'FINALIZE_SETUP';
exports.FINALIZE_SETUP = FINALIZE_SETUP;
var MOVE_DOWN = 'MOVE_DOWN';
exports.MOVE_DOWN = MOVE_DOWN;
var MOVE_UP = 'MOVE_UP';
exports.MOVE_UP = MOVE_UP;
var QUERY = 'QUERY';
exports.QUERY = QUERY;
var REMOVE = 'REMOVE';
exports.REMOVE = REMOVE;
var RESET_MENTIONS = 'RESET_MENTIONS';
exports.RESET_MENTIONS = RESET_MENTIONS;
var RESET_QUERY = 'RESET_QUERY';
exports.RESET_QUERY = RESET_QUERY;
var SELECT = 'SELECT';
exports.SELECT = SELECT;
var SHOW_LIST = 'SHOW_LIST';
exports.SHOW_LIST = SHOW_LIST;
var SYNC_EDITOR_STATE = 'SYNC_EDITOR_STATE';
exports.SYNC_EDITOR_STATE = SYNC_EDITOR_STATE;