export default [
  'test+noname',
  'test+categorymoderator',
  'Admin Awesomesauce',
  'Josh Bell',
  'Susan Billiard',
  'Fred Bunn',
  'Primo Catorce',
  'Johnny Dillard',
  'Jaime Dole',
  'Eddie Editor',
  'Peter Hunt',
  'Charles Kuralt',
  'Trini Lopez',
  'Guest McGuesterson',
  'Lucy Mills',
  'Mister Moderator',
  'Missus Moderator',
  'Gemin Starbuck',
  'Clark Superadmin',
  'Billy Thorne',
  'User Userberg'
];
