#!/bin/sh -e

BIN = ./node_modules/.bin

git checkout gh-pages
git merge master
@$(BIN)/webpack --config webpack.config.js
git add --all .
git commit -m "New release"
git push origin gh-pages
git checkout master
